# coding: utf-8

"""
    Vipps signup API

    Vipps Signup API enables a partner to initiate Vipps onboarding process on behalf of a merchant. The merchant needs to complete Vipps signup form to sign the merchant agreement with Vipps. After the signup form has been processed, Vipps will send the API keys to the defined callback endpoint. In order to complete the integration there is a need to: 1. Initiate the Signup to the Initiate endpoint 2. Accept the callback sent to the callback endpoint 3. Return a 202 response to acknowledge that the callback has been accepted.    # noqa: E501

    OpenAPI spec version: 1.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.signup_callback_api import SignupCallbackApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSignupCallbackApi(unittest.TestCase):
    """SignupCallbackApi unit test stubs"""

    def setUp(self):
        self.api = api.signup_callback_api.SignupCallbackApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_callback(self):
        """Test case for callback

        Sent Callback  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
