# coding: utf-8

# flake8: noqa
"""
    Vipps signup API

    Vipps Signup API enables a partner to initiate Vipps onboarding process on behalf of a merchant. The merchant needs to complete Vipps signup form to sign the merchant agreement with Vipps. After the signup form has been processed, Vipps will send the API keys to the defined callback endpoint. In order to complete the integration there is a need to: 1. Initiate the Signup to the Initiate endpoint 2. Accept the callback sent to the callback endpoint 3. Return a 202 response to acknowledge that the callback has been accepted.    # noqa: E501

    OpenAPI spec version: 1.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.callback_trigger_response import CallbackTriggerResponse
from swagger_client.models.partial_signup import PartialSignup
from swagger_client.models.partial_signup_response import PartialSignupResponse
from swagger_client.models.subscription_keys import SubscriptionKeys
from swagger_client.models.subscription_keys_inner import SubscriptionKeysInner
